FROM docker.elastic.co/elasticsearch/elasticsearch:7.8.0-arm64
#RUN elasticsearch-plugin install analysis-kuromoji
RUN elasticsearch-plugin install -b https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.8.0/elasticsearch-analysis-ik-7.8.0.zip

